name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'amazon-corretto'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build -t scalable-api-framework .
          echo "${{ secrets.AWS_ECR_LOGIN }}" | docker login -u AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}
          docker tag scalable-api-framework:latest ${{ secrets.AWS_ECR_REGISTRY }}/scalable-api-framework:latest
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/scalable-api-framework:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name scalable-api-framework \
            --image-uri ${{ secrets.AWS_ECR_REGISTRY }}/scalable-api-framework:latest \
            --region ${{ secrets.AWS_REGION }}
